"""
Biological Interpretation Layer
=================================
Maps SHAP feature importance to neuroscientific domain knowledge.

This module bridges the gap between "which features the model uses"
and "what those features mean biologically." Every QEEG feature in
the pipeline has a neurophysiological interpretation grounded in
published literature.

Usage:
    from utils.bio_interpretation import interpret_biomarkers
    annotated = interpret_biomarkers(shap_importance_df)
"""

# Biological annotation database
# Each entry: feature_prefix -> {system, mechanism, ef_relevance, references}
BIOMARKER_ANNOTATIONS = {
    # ── Theta/Beta Ratio ──
    "tbr_": {
        "system": "Cortical arousal regulation",
        "mechanism": (
            "TBR reflects the balance between slow-wave (theta, 4-8 Hz) and "
            "fast-wave (beta, 13-30 Hz) activity. Elevated TBR at frontal sites "
            "indicates cortical hypoarousal — reduced tonic alertness associated "
            "with prefrontal hypofunction."
        ),
        "ef_relevance": (
            "Higher frontal TBR is consistently associated with poorer executive "
            "function, particularly sustained attention and inhibitory control. "
            "The neurochemical basis involves dopaminergic and noradrenergic "
            "modulation of prefrontal cortex."
        ),
        "direction": "Higher TBR -> Lower EF (negative correlation expected)",
        "references": [
            "Arns et al. (2013) J Attention Disorders",
            "Zhang et al. (2017) Clinical Neurophysiology",
            "Tan et al. (2024) systematic review",
        ],
    },

    # ── Power Spectral Density ──
    "psd_abs_theta_": {
        "system": "Frontal theta oscillations",
        "mechanism": (
            "Resting-state frontal theta power reflects default-mode cortical "
            "activity. In children, elevated theta at rest is a maturational "
            "marker — it decreases with age as prefrontal cortex matures."
        ),
        "ef_relevance": (
            "Excessive resting theta at frontal sites (Fz, F3, F4) indicates "
            "cortical immaturity or hypoarousal. Associated with working memory "
            "deficits and reduced cognitive control."
        ),
        "direction": "Higher theta -> Lower EF",
        "references": [
            "Zhou et al. (2023) — N=5,207 children",
            "Barry et al. (2003) Clinical Neurophysiology",
        ],
    },
    "psd_abs_alpha_": {
        "system": "Thalamocortical alpha rhythm",
        "mechanism": (
            "Alpha (8-13 Hz) reflects thalamocortical idle activity. "
            "In resting state, alpha power indicates cortical inhibition "
            "of task-irrelevant processing."
        ),
        "ef_relevance": (
            "Moderate alpha power is healthy. Reduced posterior alpha may "
            "indicate difficulty disengaging from visual processing. Alpha "
            "reactivity (EC vs EO) reflects cortical responsiveness."
        ),
        "direction": "Context-dependent",
        "references": [
            "Klimesch (2012) Brain Research Reviews",
        ],
    },
    "psd_abs_beta_": {
        "system": "Cortical activation / vigilance",
        "mechanism": (
            "Beta (13-30 Hz) reflects active cortical processing, "
            "tonic alertness, and sensorimotor readiness. Generated by "
            "reticular activating system projections to cortex."
        ),
        "ef_relevance": (
            "Beta power at frontal sites relates to executive readiness. "
            "Low beta may indicate reduced vigilance. Beta is the denominator "
            "in TBR, so its relationship to EF is partly captured by TBR."
        ),
        "direction": "Higher beta -> Higher EF (generally)",
        "references": [
            "Engel & Fries (2010) Current Opinion in Neurobiology",
        ],
    },
    "psd_rel_": {
        "system": "Relative spectral composition",
        "mechanism": (
            "Relative power normalizes by total power, removing individual "
            "differences in skull thickness, electrode impedance, and overall "
            "signal amplitude. More comparable across subjects than absolute power."
        ),
        "ef_relevance": "Same as corresponding absolute band, but normalized.",
        "direction": "Band-dependent",
        "references": [],
    },

    # ── Frontal Alpha Asymmetry ──
    "faa_": {
        "system": "Motivational approach-withdrawal",
        "mechanism": (
            "FAA = ln(alpha_F4) - ln(alpha_F3). Positive values indicate "
            "greater left frontal activity, associated with approach motivation. "
            "Negative values indicate withdrawal tendency."
        ),
        "ef_relevance": (
            "FAA relates to the 'hot' executive function dimension — emotion "
            "regulation, reward sensitivity, and motivational control. "
            "May index individual differences in self-regulation strategy."
        ),
        "direction": "Positive FAA -> approach motivation -> potentially better hot EF",
        "references": [
            "Coan & Allen (2004) Biological Psychology",
            "Harmon-Jones (2003) Psychophysiology",
        ],
    },

    # ── Alpha Reactivity ──
    "alpha_reactivity": {
        "system": "Cortical responsiveness",
        "mechanism": (
            "Alpha desynchronization from eyes-closed to eyes-open reflects "
            "the cortex's ability to transition from idle to active state. "
            "Normal reactivity > 0 (alpha decreases when eyes open)."
        ),
        "ef_relevance": (
            "Reduced alpha reactivity may indicate impaired arousal modulation, "
            "which is a prerequisite for effective executive control. "
            "Associated with attention regulation capacity."
        ),
        "direction": "Higher reactivity -> Better arousal modulation -> Better EF",
        "references": [
            "Tan et al. (2024) systematic review",
        ],
    },

    # ── Coherence ──
    "coh_": {
        "system": "Functional connectivity",
        "mechanism": (
            "Coherence measures phase synchronization between channel pairs. "
            "Fronto-parietal coherence (Fz-Pz, F3-P3, F4-P4) reflects the "
            "functional coupling between prefrontal control regions and "
            "parietal visuospatial processing."
        ),
        "ef_relevance": (
            "Fronto-parietal coherence in the beta band is a marker of "
            "executive control network integrity. Higher coherence indicates "
            "more efficient information transfer between frontal executive "
            "regions and posterior processing areas."
        ),
        "direction": "Higher fronto-parietal coherence -> Better EF (in beta band)",
        "references": [
            "Sauseng et al. (2005) NeuroImage",
            "Murias et al. (2007) Biological Psychiatry",
        ],
    },

    # ── Hjorth Parameters ──
    "hjorth_activity_": {
        "system": "Signal variance (total power proxy)",
        "mechanism": "Variance of the EEG signal. Proxy for total power.",
        "ef_relevance": "Reflects overall cortical activation level.",
        "direction": "Context-dependent",
        "references": ["Hjorth (1970) Electroencephalography and Clinical Neurophysiology"],
    },
    "hjorth_mobility_": {
        "system": "Mean frequency proxy",
        "mechanism": "Ratio of derivative variance to signal variance. Proportional to mean frequency.",
        "ef_relevance": "Higher mobility = faster dominant frequency = more cortical activation.",
        "direction": "Higher mobility -> more activated cortex",
        "references": ["Hjorth (1970)"],
    },
    "hjorth_complexity_": {
        "system": "Bandwidth / signal complexity",
        "mechanism": "Deviation from a pure sine wave. Higher complexity = broader frequency content.",
        "ef_relevance": "May reflect complexity of neural processing.",
        "direction": "Context-dependent",
        "references": ["Hjorth (1970)"],
    },

    # ── Spectral Entropy ──
    "spectral_entropy_": {
        "system": "Signal regularity / complexity",
        "mechanism": (
            "Shannon entropy of the normalized PSD. Measures how uniformly "
            "distributed power is across frequencies."
        ),
        "ef_relevance": (
            "Higher entropy = more complex/irregular brain activity. "
            "May reflect cognitive flexibility or, at extremes, disorganized processing."
        ),
        "direction": "Moderate entropy optimal; very high or low may indicate dysfunction",
        "references": [
            "Inouye et al. (1991) Electroencephalography and Clinical Neurophysiology",
        ],
    },

    # ── Phase-Amplitude Coupling ──
    "pac_theta_beta_": {
        "system": "Cross-frequency coupling",
        "mechanism": (
            "Modulation of beta amplitude by theta phase. Reflects hierarchical "
            "organization of neural oscillations — theta sets the temporal window, "
            "beta implements the processing within that window."
        ),
        "ef_relevance": (
            "Theta-beta PAC at frontal sites may index the coordination between "
            "executive control (theta) and motor/cognitive readiness (beta). "
            "Disrupted PAC is observed in ADHD."
        ),
        "direction": "Higher PAC -> stronger cross-frequency coordination",
        "references": [
            "Canolty & Knight (2010) Trends in Cognitive Sciences",
        ],
    },

    # ── Quantum-Inspired Features ──
    "qepp_": {
        "system": "Non-linear phase coupling (quantum-inspired)",
        "mechanism": (
            "Interference patterns between channel pairs, computed via "
            "analytic signal representation. Mathematically equivalent to "
            "the real part of coherency, capturing phase-coupling dynamics."
        ),
        "ef_relevance": "Exploratory — may capture non-linear inter-channel dependencies missed by standard coherence.",
        "direction": "Exploratory",
        "references": ["Alotaibi et al. (2026) Scientific Reports"],
    },
    "qi_": {
        "system": "Non-classical band-power interactions",
        "mechanism": (
            "Tests whether joint distribution of band powers deviates from "
            "the product of marginals (independence assumption)."
        ),
        "ef_relevance": "Exploratory — if interference terms predict EF, suggests non-linear oscillatory interactions.",
        "direction": "Exploratory",
        "references": ["Busemeyer & Bruza (2012) Quantum Models of Cognition"],
    },
    "tn_": {
        "system": "Information-theoretic channel coupling",
        "mechanism": (
            "Von Neumann entropy and purity of the covariance matrix treated "
            "as a density matrix. Measures effective dimensionality of "
            "multi-channel EEG activity."
        ),
        "ef_relevance": "High entropy = channels are highly coupled. Low entropy = channels are independent.",
        "direction": "Exploratory",
        "references": ["Khrennikov & Yamada (2025) Frontiers in Human Neuroscience"],
    },
}


def interpret_biomarkers(importance_df):
    """
    Annotate SHAP importance DataFrame with biological interpretation.

    Args:
        importance_df: DataFrame with 'feature' and 'mean_abs_shap' columns

    Returns:
        DataFrame with added columns: system, mechanism, ef_relevance,
        direction, references
    """
    annotations = []

    for _, row in importance_df.iterrows():
        feature = row["feature"]
        matched = False

        for prefix, info in BIOMARKER_ANNOTATIONS.items():
            if feature.startswith(prefix):
                annotations.append({
                    "feature": feature,
                    "neural_system": info["system"],
                    "mechanism": info["mechanism"],
                    "ef_relevance": info["ef_relevance"],
                    "expected_direction": info.get("direction", "Unknown"),
                    "key_references": "; ".join(info.get("references", [])),
                })
                matched = True
                break

        if not matched:
            annotations.append({
                "feature": feature,
                "neural_system": "Unknown",
                "mechanism": "No annotation available",
                "ef_relevance": "Not yet characterized",
                "expected_direction": "Unknown",
                "key_references": "",
            })

    ann_df = pd.DataFrame(annotations)

    # Merge with original importance
    import pandas as pd
    result = importance_df.merge(ann_df, on="feature", how="left")
    return result


def print_biomarker_report(importance_df, top_n=10):
    """
    Print a human-readable biomarker interpretation report.
    """
    annotated = interpret_biomarkers(importance_df)

    print("\n" + "=" * 70)
    print("BIOMARKER INTERPRETATION REPORT")
    print("=" * 70)

    for i, (_, row) in enumerate(annotated.head(top_n).iterrows()):
        rank = i + 1
        print(f"\n{'─' * 70}")
        print(f"  #{rank}: {row['feature']}")
        print(f"  SHAP importance: {row['mean_abs_shap']:.4f}")
        if "shap_cv" in row:
            stability = "STABLE" if row["shap_cv"] < 0.5 else "UNSTABLE"
            print(f"  Stability: {stability} (CV={row['shap_cv']:.2f})")
        print(f"  Neural system: {row['neural_system']}")
        print(f"  Expected direction: {row['expected_direction']}")
        print(f"  EF relevance: {row['ef_relevance']}")
        if row["key_references"]:
            print(f"  Key refs: {row['key_references']}")

    print(f"\n{'=' * 70}")
    print("NOTE: Interpretations are based on published literature.")
    print("Quantum-inspired features are EXPLORATORY and require validation.")
    print(f"{'=' * 70}")


# Needed for interpret_biomarkers
import pandas as pd
